

UPDATE  TBL_PRODUTO_PRECO SET
    TBL_PRODUTO_PRECO.VL_VAREJO12       =  TBL_PRODUTO_PRECO.VL_VAREJO1,
    TBL_PRODUTO_PRECO.VL_ATACADO12      =  TBL_PRODUTO_PRECO.VL_ATACADO1,
    TBL_PRODUTO_PRECO.VL_CORPORATIVO12  =  TBL_PRODUTO_PRECO.VL_CORPORATIVO1

 WHERE
 TBL_PRODUTO_PRECO.ID_SYSTEM_CLIENTE = 14

UPDATE  TBL_PRODUTO_PRECO SET
    TBL_PRODUTO_PRECO.VL_VAREJO13       =  TBL_PRODUTO_PRECO.VL_VAREJO1,
    TBL_PRODUTO_PRECO.VL_ATACADO13      =  TBL_PRODUTO_PRECO.VL_ATACADO1,
    TBL_PRODUTO_PRECO.VL_CORPORATIVO13  =  TBL_PRODUTO_PRECO.VL_CORPORATIVO1

 WHERE
 TBL_PRODUTO_PRECO.ID_SYSTEM_CLIENTE = 14