 UPDATE  TBL_PRODUTO SET
     TBL_PRODUTO.FLAG_WEBSITE_OFF = 1
  WHERE TBL_PRODUTO.ID_SYSTEM_CLIENTE = 14
  and
   TBL_PRODUTO.FLAG_WEBSITE_OFF = 0
 AND
 EXISTS (
             SELECT
              TBL_PRODUTO_OFF.ID_TBL_PRODUTO
            FROM
             TBL_PRODUTO  AS TBL_PRODUTO_OFF
            INNER JOIN  TBL_PRODUTO_ESTOQUE ON TBL_PRODUTO_ESTOQUE.ID_PRODUTO = TBL_PRODUTO_OFF.ID_TBL_PRODUTO
            INNER JOIN  TBL_PRODUTO_PRECO ON TBL_PRODUTO_PRECO.ID_PRODUTO = TBL_PRODUTO_OFF.ID_TBL_PRODUTO
             WHERE TBL_PRODUTO_OFF.ID_SYSTEM_CLIENTE = 14
             AND  TBL_PRODUTO_OFF.INATIVO = 2
             AND   TBL_PRODUTO_OFF.FLAG_SERVICO = 0
             AND TBL_PRODUTO_OFF.ID_TIPO IN (1,14,18,22,22,24)
            AND
               TBL_PRODUTO_ESTOQUE.ESTOQUE_LOJA1 < 10
            AND
               TBL_PRODUTO_PRECO.VL_ATACADO1 < 100
            AND
            TBL_PRODUTO_OFF.ID_TBL_PRODUTO = TBL_PRODUTO.ID_TBL_PRODUTO
        )



SELECT
   TBL_PRODUTO.ID_TBL_PRODUTO,
   TBL_PRODUTO.PRODUTO,
   TBL_PRODUTO_ESTOQUE.ESTOQUE_LOJA1,
   TBL_PRODUTO_PRECO.VL_ATACADO1
FROM
 TBL_PRODUTO
INNER JOIN  TBL_PRODUTO_ESTOQUE ON TBL_PRODUTO_ESTOQUE.ID_PRODUTO = TBL_PRODUTO.ID_TBL_PRODUTO
INNER JOIN  TBL_PRODUTO_PRECO ON TBL_PRODUTO_PRECO.ID_PRODUTO = TBL_PRODUTO.ID_TBL_PRODUTO
 WHERE TBL_PRODUTO.ID_SYSTEM_CLIENTE = 14
 AND   TBL_PRODUTO.INATIVO = 2
 AND   TBL_PRODUTO.FLAG_SERVICO = 0
 AND TBL_PRODUTO.ID_TIPO IN (1,14,18,22,22,24)
AND
   TBL_PRODUTO_ESTOQUE.ESTOQUE_LOJA1 < 10
AND
   TBL_PRODUTO_PRECO.VL_ATACADO1 < 100
ORDER BY
 TBL_PRODUTO.PRODUTO