 SELECT
    TBL_PRODUTO.ID_TBL_PRODUTO as ID_PRODUTO,
    TBL_PRODUTO.PRODUTO,
    TBL_PRODUTO_ESTOQUE.ESTOQUE_LOJA1,
    TBL_PRODUTO_PRECO.VL_ATACADO1,
    TBL_PRODUTO_PRECO.VL_VAREJO1,

    TBL_PRODUTO.ID_IMAGEM,
    TBL_PRODUTO.PATH_IMAGEM,
    TBL_PRODUTO.PATH_PAGE
FROM
TBL_PRODUTO
INNER JOIN TBL_PRODUTO_ESTOQUE      ON  TBL_PRODUTO_ESTOQUE.ID_PRODUTO     =   TBL_PRODUTO.ID_TBL_PRODUTO
LEFT JOIN TBL_PRODUTO_PRECO      ON  TBL_PRODUTO_PRECO.ID_PRODUTO           =   TBL_PRODUTO.ID_TBL_PRODUTO
WHERE
    TBL_PRODUTO.ID_SYSTEM_CLIENTE =  14
AND
    TBL_PRODUTO.INATIVO = 2
AND
TBL_PRODUTO_ESTOQUE.ESTOQUE_LOJA8 > 0

AND
   (( TBL_PRODUTO_PRECO.VL_ATACADO1 > 0 ) or ( TBL_PRODUTO_PRECO.VL_VAREJO1 > 0 ))
ORDER BY
    TBL_PRODUTO.ID_TBL_PRODUTO DESC




SELECT
    TBL_PRODUTO.ID_TBL_PRODUTO as ID_PRODUTO,
    TBL_PRODUTO.ID_POST,
    TBL_PRODUTO.PRODUTO,
    TBL_PRODUTO_ESTOQUE.ESTOQUE_LOJA1,
    TBL_PRODUTO_PRECO.VL_ATACADO1,
    TBL_PRODUTO_PRECO.VL_VAREJO1,
    TBL_PRODUTO_ESTOQUE.ESTOQUE_LOJA8,
    TBL_PRODUTO_PRECO.VL_ATACADO8,
    TBL_PRODUTO_PRECO.VL_VAREJO8,


    TBL_PRODUTO.ID_IMAGEM,
    TBL_PRODUTO.PATH_IMAGEM,
    TBL_PRODUTO.PATH_PAGE,
    TBL_PRODUTO.ID_FAMILIA,
    TBL_PRODUTO.ID_GRUPO,
    TBL_PRODUTO.ID_SUBGRUPO,
    TBL_PRODUTO.FLAG_WEBSITE_OFF,
    TBL_PRODUTO.IMPORTADO,
    TBL_PRODUTO.DESTAQUE,
    TBL_PRODUTO.PESO_GR,
    TBL_PRODUTO.COMPRIMENTO_MM,
    TBL_PRODUTO.LARGURA_MM,
    TBL_PRODUTO.ALTURA_MM,
    TBL_PRODUTO.DIAMETRO_MM,
    TBL_PRODUTO.SALEUNIT,
    TBL_PRODUTO.QT_SALEUNIT,
    TBL_PRODUTO.TEMPODEGARANTIA_MES,
    TBL_PRODUTO.DT_UPD_WEBSITE,
    TBL_PRODUTO.DATA_ULT_ENTRADA,
    TBL_PRODUTO.DATADOCADASTRO
FROM
TBL_PRODUTO
INNER JOIN TBL_PRODUTO_ESTOQUE      ON  TBL_PRODUTO_ESTOQUE.ID_PRODUTO     =   TBL_PRODUTO.ID_TBL_PRODUTO
LEFT JOIN TBL_PRODUTO_PRECO      ON  TBL_PRODUTO_PRECO.ID_PRODUTO           =   TBL_PRODUTO.ID_TBL_PRODUTO
WHERE
    TBL_PRODUTO.ID_SYSTEM_CLIENTE =  :PE_ID_SYSTEM
AND
    TBL_PRODUTO.INATIVO = 2
AND
TBL_PRODUTO_ESTOQUE.ESTOQUE_LOJA8 > 0
AND
   (( TBL_PRODUTO_PRECO.VL_ATACADO1 > 0 ) or ( TBL_PRODUTO_PRECO.VL_VAREJO1 > 0 ))
ORDER BY
    TBL_PRODUTO.ID_TBL_PRODUTO DESC












